export * from "./landing";
export * from "./tutorials";
export * from "./error";
export * from "./FAQ";
export * from "./about";
export * from "./profile";
export * from "./admin";
export * from "./setPassword";
export * from "./terms";